authority/urls.py
from django.conf.urls import url
from authority import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^register/$', views.register),
    url(r'^loginview/$', views.loginview),
    url(r'^myadmin/$', views.myadmin),
    url(r'^logoutview/$', views.logoutview),
    url(r'^user_list/$', views.user_list),
    url(r'^add_user/$', views.add_user),
    url(r'^add_user_detail/$', views.add_user_detail),
    url(r'^change_pwd/$', views.change_pwd),
    url(r'^group_list/$', views.group_list),
    url(r'^add_group/$', views.add_group),
    url(r'^delete_group/$',views.delete_group),
    url(r'^delete_user/$', views.delete_user),
    url(r'^register1/$', views.register),
    url(r'^add_user_details/(\d+)/', views.users_detail),
    url(r'^groups_detail/(\d+)/', views.groups_detail),
    url(r'^change_group_permission/(\d+)/', views.change_group_permission),
    url(r'^show_devices/(\d+)/', views.show_devices),
]

django_yun/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^authority/', include('authority.urls')),
    url(r'^', include('message.urls')),

]

message/urls.py
from django.conf.urls import url
from message.views import IndexView
from message import views
urlpatterns = [
    url(r'^$', IndexView.as_view()),
    url(r'^board$', views.board),
    url(r'^get_tips$', views.get_tips),
    url(r'^get_device$', views.get_device),
    url(r'^register/$', views.register),
    url(r'^manager/$', views.manager),
]

authority/models.py
from django.db import models

message/models.py
from django.db import models


# Create your models here.
class Device(models.Model):
    mac = models.CharField(max_length=64)                # mac地址
    name = models.CharField(max_length=64)               # 设备名称
    type = models.CharField(max_length=64)               # 设备的类型
    Firmware = models.CharField(max_length=64)           # 设备固件
    note = models.CharField(max_length=64)               # 评论
    active_time = models.DateField()                     # 激活时间
    version = models.CharField(max_length=64)            # 版本号
    online_time = models.DateField()                     # 最后一次上线时间
    offline_time = models.DateField()                    # 最后一次下线时间
    user_name = models.CharField(max_length=64)          # 用户名


class Team(models.Model):
    name = models.CharField(max_length=64)               # 设备组名称
    user_name = models.CharField(max_length=64)          # 用户名
    device = models.ForeignKey(Device)                   # 和设备间建立外键关系

authority/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User, Permission, Group
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.contenttypes.models import ContentType


def index(request):
    return HttpResponse('这是首页')


def register(request):
    if request.method == 'GET':
        return render(request, 'authority/register.html')
    else:
        username = request.POST.get('username')
        password = request.POST.get('password')
        email = '123@123.com'
        try:
            user = User.objects.create_user(username, email, password)
        except Exception as e:
            return HttpResponse('注册用户失败')
        user.is_active = 1
        user.is_staff = 1
        user.save()
        return redirect('/authority/add_user_detail/')


def loginview(request):
    if request.method == 'GET':
        return render(request, 'authority/login.html')
    else:
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)
        if user is None:
            return HttpResponse('用户名或密码错误')
        else:
            login(request, user)
            return redirect('/authority/myadmin')


@login_required()
def logoutview(request):
    logout(request)
    return redirect('/authority/loginview/')


@login_required()
def myadmin(request):
    user = request.user
    models = ContentType.objects.filter(app_label='message').all()
    list1 = []
    list2 = []
    model_list = []
    for model in models:
        model_list.append(model)
    device = model_list[0]
    team = model_list[1]
    content_type = ContentType.objects.get(id=device.id)
    model_permissions = content_type.permission_set.all()
    list = []
    for permission in model_permissions:
        list.append(permission.id)
    permissions = user.user_permissions.filter(id__in=list)
    for permission in permissions:
        list1.append(permission.id)

    content_type = ContentType.objects.get(id=team.id)
    model_permissions = content_type.permission_set.all()
    list = []
    for permission in model_permissions:
        list.append(permission.id)
    permissions = user.user_permissions.filter(id__in=list)
    for permission in permissions:
        list2.append(permission.id)
    context = {
        'device': device,
        'team': team,
        'list1': list1,
        'list2': list2,
    }
    return render(request, 'authority/myadmin.html', context)


@login_required()
def user_list(request):
    users = User.objects.all()
    context = {
        'users': users
    }
    return render(request, 'authority/user_list.html', context)


@login_required()
def add_user(request):
    if request.method == 'GET':
        return render(request, 'authority/add_user.html')
    else:
        username = request.POST.get('username')
        password = request.POST.get('password1')
        password2 = request.POST.get('password2')
        email = request.POST.get('email')
        if not all([username, password, password2]):
            return HttpResponse('请将信息输入完整')
        if password == password2:
            try:
                user1 = User.objects.create_user(username, email, password)
                user1.save()
            except Exception as e:
                return HttpResponse('创建用户失败')

            user = request.user
            if user.is_superuser:
                groups = Group.objects.all()
                permissions = Permission.objects.all()
                context = {
                    'user1': user1,
                    'groups': groups,
                    'permissions': permissions
                }
            else:
                permissions = user.user_permissions.all()
                groups = user.groups.all()
                context = {
                    'permissions': permissions,
                    'groups': groups,
                    'user1': user1,
                }
            return render(request, 'authority/add_user_datail.html', context)
        else:
            return HttpResponse('两次密码输入不一致')


@login_required()
def add_user_detail(request):
    if request.method == 'GET':
        permissions = Permission.objects.all()
        groups = Group.objects.all()
        context = {
            'permissions': permissions,
            'groups': groups
        }
        return render(request, 'authority/add_user_datail.html', context)
    else:
        username = request.POST.get('username')
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        is_active = request.POST.get('is_active')
        is_staff = request.POST.get('is_staff')
        is_superuser = request.POST.get('is_superuser')
        print(is_superuser, 3)

        try:
            user = User.objects.get(username=username)
        except Exception as e:
            return HttpResponse('查询数据库失败')

        user.first_name = first_name
        user.username = username
        user.last_name = last_name
        if is_active == 'on':
            user.is_active = 1
        else:
            user.is_active = 0
        if is_staff == 'on':
            user.is_staff = 1
        else:
            user.is_staff = 0
        if is_superuser == 'on':
            user.is_superuser = 1
        else:
            user.is_superuser = 0

        groups = Group.objects.all()
        mouth = 1
        for group in groups:
            if group.id > mouth:
                mouth = group.id
        a = 1
        group_list1 = []
        while a <= mouth:
            id = request.POST.get('group%d' % a)
            if id is not None:
                group_list1.append(id)
            a += 1
        delete_groups = user.groups.all()
        for group in delete_groups:
            user.groups.remove(group)
        for group in group_list1:
            user.groups.add(group)

        permissions = Permission.objects.all()
        count = 1
        for permission in permissions:
            if permission.id > count:
                count = permission.id
        i = 1
        permission_list = []
        while i <= count:
            id = request.POST.get('permission%d' % i)
            if id is not None:
                permission_list.append(id)
            i += 1
        delete_permissions = user.user_permissions.all()
        for permission in delete_permissions:
            user.user_permissions.remove(permission)
        for permission in permission_list:
            user.user_permissions.add(permission)
        user.save()
        return redirect('/authority/myadmin/')


@login_required()
def change_pwd(request):
    if request.method == 'GET':
        return render(request, 'authority/change_pwd.html')
    else:
        old_password = request.POST.get('old_password')
        new_password1 = request.POST.get('new_password1')
        new_password2 = request.POST.get('new_password2')
        user = request.user
        user1 = authenticate(username=user.username, password=old_password)

        if not user1:
            return HttpResponse('密码输入有误')
        if not new_password1 == new_password2:
            return HttpResponse('两次输入密码不相同')

        user1.set_password(new_password1)
        user1.save()

        return redirect('/authority/myadmin/')


@login_required()
def group_list(request):

    groups = Group.objects.all()
    count = len(groups)
    context = {
        'groups': groups,
        'count': count
    }

    return render(request, 'authority/group_list.html', context)


@login_required()
def add_group(request):
    if request.method == 'GET':
        permissions = Permission.objects.all()
        context = {
            'permissions': permissions
        }
        return render(request, 'authority/add_group.html', context)
    else:
        group_name = request.POST.get('name')
        if not group_name:
            return HttpResponse('请输入组名')
        group = Group.objects.create(name=group_name)
        if group is None:
            return HttpResponse('用户组创建失败')
        permissions = Permission.objects.all()
        count = len(permissions)
        i = 1
        permission_list = []
        while i <= count:
            id = request.POST.get('permission%d' % i)
            if id is not None:
                permission_list.append(id)
            i += 1
        for permission in permission_list:
            group.permissions.add(permission)
        group.save()
        return redirect('/authority/group_list/')


@login_required()
def delete_group(request):
    groups = Group.objects.all()
    mouth = 1
    for group in groups:
        if group.id > mouth:
            mouth = group.id
    a = 1
    group_list1 = []
    while a <= mouth:
        id = request.POST.get('group%d' % a)
        if id is not None:
            group_list1.append(id)
        a += 1

    for idd in group_list1:
        groups = Group.objects.filter(id=idd)

        for group in groups:
            group.permissions.clear()
            group.user_set.clear()
            group.delete()

    return redirect('/authority/group_list/')


@login_required()
def delete_user(request):
    users = User.objects.all()
    mouth = 1
    for user in users:
        if user.id > mouth:
            mouth = user.id
    a = 0
    user_list1 = []
    while a <= mouth:
        id = request.POST.get('user%d' % a)
        if id is not None:
            user_list1.append(id)
        a += 1

    for idd in user_list1:
        users = User.objects.filter(id=idd)
        for user in users:
            user.user_permissions.clear()
            user.groups.clear()
            user.delete()

    return redirect('/authority/user_list/')


@login_required()
def users_detail(request, page):
    permissions = Permission.objects.all()
    groups = Group.objects.all()
    user = User.objects.get(id=page)

templates/authority/add_group.html
<!DOCTYPE html>
<html lang="zh-hans" >
<head>
<title>增加 组</title>
</head>
<body class=" app-auth model-group change-form">
<div id="container">
    <div id="header">
        <div id="branding">
        <h1 id="site-name"><a href="/authority/myadmin/">Django 管理</a></h1>
        </div>
        <div id="user-tools">
                欢迎，
                <strong>{{ user.username }}</strong>
                    <a href="/">查看站点</a> /
                <a href="/authority/change_pwd/">修改密码</a> /

                <a href="/authority/logoutview/">注销</a>
        </div>
    </div>
    <div id="content" class="colM">
        <h1>增加 组</h1>
        <div id="content-main">
        <form enctype="multipart/form-data" action="/authority/add_group/" method="post" id="group_form" novalidate>
        <div>
            <fieldset class="module aligned ">
                <div class="form-row field-name">
                    <div>
                        <label class="required" for="id_name">名称:</label>
                        <input class="vTextField" id="id_name" maxlength="80" name="name" type="text" value="{{ group.name }}" />
                    </div>
                </div>
                <div class="form-row field-permissions">

                        <label for="id_permissions">权限:</label>
                <div class="form-row field-user_permissions">
                {% load filters %}
                    {% for permission in permissions %}
                        <div class="checkbox-row">
                            <input id="id_is_superuser" value="{{ permission.id}}" name="permission{{ permission.id }}" type="checkbox" /><label class="vCheckboxLabel" for="id_is_superuser">{{ permission.name }}.{{ permission.codename }}</label>
                        </div>
                    {% endfor %}
                </div>
                    <p class="help">按住 ”Control“，或者Mac上的 “Command”，可以选择多个。</p>
                </div>
            </fieldset>
        <div class="submit-row">
        <input type="submit" value="保存" class="default" name="_save" />
        </div>
        </div>
        </form>
        </div>
    </div>
</div>
</body>
</html>

templates/authority/add_user.html
<!DOCTYPE html>

<html lang="zh-Hans" >

<head>
<title>增加 用户 | Django 站点管理员</title>
</head>

<body class=" app-auth model-user change-form">

    <div id="container">

        <div id="header">
            <div id="branding">
            <h1 id="site-name"><a href="/admin/">Django 管理</a></h1>
            </div>
            <div id="user-tools">
                    欢迎，
                    <strong>{{ user.username }}</strong>
                        <a href="/">查看站点</a> /
                    <a href="/admin/password_change/">修改密码</a> /

                    <a href="/logoutview/">注销</a>
            </div>
        </div>

    <div id="content" class="colM">
        <h1>增加 用户</h1>

        <div id="content-main">
        <form action="/authority/add_user/" method="post" id="user_form">
            <p>首先，输入一个用户名和密码。然后，你就可以编辑更多的用户选项。</p>
            <div>
                <fieldset class="module aligned wide">
                    <div class="form-row field-username">
                        <div>
                            <label class="required" for="id_username">用户名:</label>
                            <input class="vTextField" id="id_username" maxlength="30" name="username" type="text" />
                            <p class="help">必填。不多于30个字符。只能用字母、数字和字符 @/./+/-/_ 。</p>
                        </div>
                    </div>
                    <div class="form-row field-password1">
                        <div>
                            <label class="required" for="id_password1">密码:</label>
                            <input id="id_password1" name="password1" type="password" />
                        </div>
                    </div>
                    <div class="form-row field-password2">
                        <div>
                            <label class="required" for="id_password2">密码确认:</label>
                            <input id="id_password2" name="password2" type="password" />
                            <p class="help">为了校验，输入与上面相同的密码。</p>
                        </div>
                    </div>
                    <div class="form-row field-email">
                        <div>
                            <label for="id_email">电子邮件地址:</label>
                            <input class="vTextField" id="id_email" maxlength="254" name="email" type="email" />
                        </div>
                    </div>
                </fieldset>
            <div class="submit-row">
            <input type="submit" value="保存" class="default" name="_save" />

            </div>
            </div>
        </form>
        </div>

        </div>
    </div>
</body>
</html>

templates/authority/add_user_datail.html
<!DOCTYPE html>

<html lang="zh-Hans" >
<head>
<title>修改 用户</title>
</head>

<body class=" app-auth model-user change-form">

<div id="container">

    <div id="header">
        <div id="branding">
        <h1 id="site-name"><a href="/admin/">Django 管理</a></h1>
        </div>
        <div id="user-tools">
                欢迎，
                <strong>{{ user.username }}</strong>
                    <a href="/">查看站点</a> /
                <a href="/admin/password_change/">修改密码</a> /

                <a href="/logoutview/">注销</a>
        </div>
    </div>

    <div id="content" class="colM">
        <h1>修改 用户</h1>
        <div id="content-main">

        <form action="/authority/add_user_detail/" method="post" id="user_form">
        <div>
        <fieldset class="module aligned ">
                <div class="form-row field-username">
                        <div>
                                <label class="required" for="id_username">用户名:</label>
                                    <input class="vTextField" id="id_username" maxlength="30" name="username" type="text" value="{{ user1.username }}" />
                                <p class="help">必填。不多于30个字符。只能用字母、数字和字符 @/./+/-/_ 。</p>
                        </div>
                </div>
        </fieldset>

        <fieldset class="module aligned ">
            <h2>个人信息</h2>
                <div class="form-row field-first_name">
                        <div>
                                <label for="id_first_name">名字:</label>
                                    <input class="vTextField" id="id_first_name" maxlength="30" name="first_name" type="text" value="{{ user1.first_name }}" />
                        </div>
                </div>
                <div class="form-row field-last_name">
                        <div>
                                <label for="id_last_name">姓氏:</label>
                                    <input class="vTextField" id="id_last_name" maxlength="30" name="last_name" type="text" value="{{ user1.last_name }}" />
                        </div>
                </div>

        </fieldset>

        <fieldset class="module aligned ">
            <h2>权限</h2>
                <div class="form-row field-is_active">
                        <div class="checkbox-row">
                                <input checked="checked" id="id_is_active" name="is_active" type="checkbox" /><label class="vCheckboxLabel" for="id_is_active">有效</label>
                                <p class="help">指明用户是否被认为活跃的。以反选代替删除帐号。</p>
                        </div>
                </div>
                <div class="form-row field-is_staff">
                        <div class="checkbox-row">
                                <input id="id_is_staff" name="is_staff" type="checkbox" {% if user1.is_staff %} checked="checked" {% endif %} /><label class="vCheckboxLabel" for="id_is_staff">职员状态</label>
                                <p class="help">指明用户是否可以登录到这个管理站点。</p>
                        </div>
                </div>
                <div class="form-row field-is_superuser">
                {% if user.is_superuser %}
                        <div class="checkbox-row">
                                <input id="id_is_superuser" name="is_superuser" type="checkbox" {% if user1.is_superuser %} checked="checked" {% endif %} /><label class="vCheckboxLabel" for="id_is_superuser">超级用户状态</label>
                                <p class="help">指明该用户缺省拥有所有权限。</p>
                        </div>
                {% endif %}
                </div>

                <div class="form-row field-is_superuser">
                {% load filters %}
                    {% for group in groups %}
                        <div class="checkbox-row">
                            <input id="id_is_superuser" value="{{ group.id}}" name="group{{ group.id }}" type="checkbox" {% if user1.is_superuser %} checked="checked" {% elif group.id|mod:list_group %} checked="checked" {% endif %} /><label class="vCheckboxLabel" for="id_is_superuser">{{ group.name }}</label>
                        </div>
                    {% endfor %}
                </div>

                <div class="form-row field-user_permissions">
                {% load filters %}
                    {% for permission in permissions %}
                        <div class="checkbox-row">
                            <input id="id_is_superuser" value="{{ permission.id}}" name="permission{{ permission.id }}" type="checkbox" {% if user1.is_superuser %} checked="checked" {% elif permission.id|mod:list1 %} checked="checked" {% endif %} /><label class="vCheckboxLabel" for="id_is_superuser">{{ permission.name }}.{{ permission.codename }}</label>
                        </div>
                    {% endfor %}
                </div>

        </fieldset>

        <div class="submit-row">
        <input type="submit" value="保存" class="default" name="_save" />
        </div>
        </div>
        </form>
        </div>



    </div>


    <div id="footer"></div>
</div>
</body>
</html>

templates/authority/change_group_permission.html
<!DOCTYPE html>
<html lang="zh-hans" >
<head>
<title>增加 组</title>
</head>
<body class=" app-auth model-group change-form">
<div id="container">
    <div id="header">
        <div id="branding">
        <h1 id="site-name"><a href="/authority/myadmin/">Django 管理</a></h1>
        </div>
        <div id="user-tools">
                欢迎，
                <strong>{{ user.username }}</strong>
                    <a href="/">查看站点</a> /
                <a href="/authority/change_pwd/">修改密码</a> /

                <a href="/authority/logoutview/">注销</a>
        </div>
    </div>
    <div id="content" class="colM">
        <h1>增加 组</h1>
        <div id="content-main">
        <form enctype="multipart/form-data" action="/authority/change_group_permission/{{ group.id }}/" method="post" id="group_form" novalidate>
        <div>
            <fieldset class="module aligned ">
                <div class="form-row field-name">
                    <div>
                        <label class="required" for="id_name">名称:</label>
                        <input class="vTextField" id="id_name" maxlength="80" name="name" type="text" value="{{ group.name }}" />
                    </div>
                </div>
                <div class="form-row field-permissions">

                        <label for="id_permissions">权限:</label>
                <div class="form-row field-user_permissions">
                {% load filters %}
                    {% for permission in permissions %}
                        <div class="checkbox-row">
                            <input id="id_is_superuser" value="{{ permission.id}}" name="permission{{ permission.id }}" type="checkbox" {% if permission.id|mod:list1 %} checked="checked" {% endif %} /><label class="vCheckboxLabel" for="id_is_superuser">{{ permission.name }}.{{ permission.codename }}</label>
                        </div>
                    {% endfor %}
                </div>
                    <p class="help">按住 ”Control“，或者Mac上的 “Command”，可以选择多个。</p>
                </div>
            </fieldset>
        <div class="submit-row">
        <input type="submit" value="保存" class="default" name="_save" />
        </div>
        </div>
        </form>
        </div>
    </div>
</div>
</body>
</html>

templates/authority/change_pwd.html
<!DOCTYPE html>
<html lang="zh-hans" >
<head>
<title>密码修改</title>
</head>


<body class="">

<div id="container">
    <div id="header">
        <div id="branding">
        <h1 id="site-name"><a href="/admin/">Django 管理</a></h1>
        </div>
        <div id="user-tools">
                欢迎，
                <strong>{{ user.username }}</strong>
                    <a href="/">查看站点</a> /
                <a href="/admin/password_change/">修改密码</a> /

                <a href="/logoutview/">注销</a>
        </div>
    </div>

    <div class="breadcrumbs">
    <a href="/admin/">首页</a>
    &rsaquo; 密码修改
    </div>

    <div id="content" class="colM">
        <h1>密码修改</h1>
        <div id="content-main">
        <form action="" method="post">
        <div>
        <p>请输入你的旧密码，为了安全起见，接着要输入两遍新密码，以便我们校验你输入的是否正确。</p>

        <fieldset class="module aligned wide">
            <div class="form-row">
                <label class="required" for="id_old_password">旧密码:</label> <input id="id_old_password" name="old_password" type="password" />
            </div>

            <div class="form-row">
                <label class="required" for="id_new_password1">新密码:</label> <input id="id_new_password1" name="new_password1" type="password" />
            </div>

            <div class="form-row">
                <label class="required" for="id_new_password2">新密码确认:</label> <input id="id_new_password2" name="new_password2" type="password" />
            </div>
        </fieldset>

        <div class="submit-row">
            <input type="submit" value="修改我的密码" class="default" />
        </div>

        </div>
        </form>
        </div>

    </div>

</div>

</body>
</html>

templates/authority/group_list.html
<!DOCTYPE html>
<html lang="zh-hans" >
<head>
<title>选择 组 来修改</title>
</head>
<body class=" app-auth model-group change-list">
<div id="container">
    <div id="header">
        <div id="branding">
        <h1 id="site-name"><a href="/authority/myadmin/">Django 管理</a></h1>
        </div>
        <div id="user-tools">
                欢迎，
                <strong>{{ user.username }}</strong>
                    <a href="/">查看站点</a> /
                <a href="/authority/change_pwd/">修改密码</a> /

                <a href="/authority/logoutview/">注销</a>
        </div>
    </div>
    <div id="content" class="flex">
        <h1>选择 组 来修改</h1>
        <div id="content-main">
            <ul class="object-tools">
                <li>
                  <a href="/authority/add_group/" class="addlink">
                    增加 组
                  </a>
                </li>
            </ul>
        <div class="module" id="changelist">
        <div id="toolbar">
            <form id="changelist-search" action="" method="get">
                <div><!-- DIV needed for valid HTML -->
                <label for="searchbar"><img src="/static/admin/img/icon_searchbox.png" alt="Search" /></label>
                <input type="text" size="40" name="q" value="" id="searchbar" />
                <input type="submit" value="搜索" />
                </div>
            </form>
        </div>
    <form id="changelist-form" action="/authority/delete_group/" method="post" novalidate>
        <div class="actions">
            <label>删除所选的 组
            </label>
            <input class="select-across" name="select_across" type="hidden" value="0" />
            <button type="submit" class="button" title="运行选中的动作" name="index" value="0">删除</button>
        </div>
        <div class="results">
        <table id="result_list">
        <thead>
            <tr>
            <th scope="col"  class="action-checkbox-column">
               <div class="text"><span><input type="checkbox" id="action-toggle" /></span></div>
               <div class="clear"></div>
            </th>
            <th scope="col"  class="column-__str__">
               <div class="text"><span>组</span></div>
               <div class="clear"></div>
            </th>
            </tr>
        </thead>
        <tbody>
        {% for group in groups %}
            <tr class="row1">
                <td class="action-checkbox">
                    <input class="action-select" name="group{{ group.id }}" type="checkbox" value="{{ group.id }}" />
                </td>
                <th class="field-__str__">
                    <a href="/authority/groups_detail/{{ group.id }}">{{ group.name }}</a>
                </th>
            </tr>
        {% endfor %}
        </tbody>
        </table>
        </div>
        <p class="paginator">
        {{ count }}
        </p>
    </form>
        </div>
      </div>
    </div>
</div>
</body>
</html>

templates/authority/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登陆页面</title>
</head>
<body>
	<form method="post" action="/authority/loginview/">
        <ul>
            <li>
                <label>用户名:</label>
                <input type="text" name="username" id="username">
            </li>
            <li>
                <label>密码:</label>
                <input type="password" name="password" id="password">
            </li>
            <li>
                <input type="submit" value="登 陆" name="登 陆">
            </li>
        </ul>
    </form>
</body>
</html>

templates/authority/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册页面</title>
</head>
<body>
	<form method="post" action="/authority/register/">
        <ul>
            <li>
                <label>用户名:</label>
                <input type="text" name="username" id="username">
            </li>
            <li>
                <label>密码:</label>
                <input type="password" name="password" id="password">
            </li>
            <li>
                <label>确认密码:</label>
                <input type="password" name="password2" id="password2">
            </li>
            <li>
                <input type="submit" value="注 册" name="注 册">
            </li>
        </ul>
    </form>
</body>
</html>